<?php
/**
 * Class LocationSeeder.
 *
 * @category Worketic
 *
 * @package Worketic
 * @author  Amentotech <theamentotech@gmail.com>
 * @license http://www.amentotech.com Amentotech
 * @link    http://www.amentotech.com
 */

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

/**
 * Class LocationSeeder
 */
class LocationSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('locations')->insert(
            [
                [
                    'title' => 'Australia',
                    'slug'  => 'australia',
                    'parent'  => 0,
                    'flag'  => 'au.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Afghanistan',
                    'slug'  => 'afghanistan',
                    'parent'  => 0,
                    'flag'  => 'af.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Albania',
                    'slug'  => 'albania',
                    'parent'  => 0,
                    'flag'  => 'al.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Algeria',
                    'slug'  => 'algeria',
                    'parent'  => 0,
                    'flag'  => 'alg.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Andorra',
                    'slug'  => 'andorra',
                    'parent'  => 0,
                    'flag'  => 'ad.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Angola',
                    'slug'  => 'angola',
                    'parent'  => 0,
                    'flag'  => 'ao.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Argentina',
                    'slug'  => 'argentina',
                    'parent'  => 0,
                    'flag'  => 'ar.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Armenia',
                    'slug'  => 'armenia',
                    'parent'  => 0,
                    'flag'  => 'am.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Austria',
                    'slug'  => 'austria',
                    'parent'  => 0,
                    'flag'  => 'at.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Azerbaijan',
                    'slug'  => 'azerbaijan',
                    'parent'  => 0,
                    'flag'  => 'az.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Bahrain',
                    'slug'  => 'bahrain',
                    'parent'  => 0,
                    'flag'  => 'bh.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Bangladesh',
                    'slug'  => 'bangladesh',
                    'parent'  => 0,
                    'flag'  => 'bd.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Barbados',
                    'slug'  => 'barbados',
                    'parent'  => 0,
                    'flag'  => 'bb.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Belarus',
                    'slug'  => 'belarus',
                    'parent'  => 0,
                    'flag'  => 'by.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Belgium',
                    'slug'  => 'belgium',
                    'parent'  => 0,
                    'flag'  => 'be.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Belize',
                    'slug'  => 'belize',
                    'parent'  => 0,
                    'flag'  => 'bz.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Benin',
                    'slug'  => 'benin',
                    'parent'  => 0,
                    'flag'  => 'bj.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Bolivia',
                    'slug'  => 'bolivia',
                    'parent'  => 0,
                    'flag'  => 'bo.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Bosnia',
                    'slug'  => 'bosnia',
                    'parent'  => 0,
                    'flag'  => 'ba.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Botswana',
                    'slug'  => 'botswana',
                    'parent'  => 0,
                    'flag'  => 'bw.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Brazil',
                    'slug'  => 'brazil',
                    'parent'  => 0,
                    'flag'  => 'br.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Brunei',
                    'slug'  => 'brunei',
                    'parent'  => 0,
                    'flag'  => 'bn.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Bulgaria',
                    'slug'  => 'bulgaria',
                    'parent'  => 0,
                    'flag'  => 'bg.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Burkina Faso',
                    'slug'  => 'burkina-faso',
                    'parent'  => 0,
                    'flag'  => 'bf.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Myanmar',
                    'slug'  => 'myanmar',
                    'parent'  => 0,
                    'flag'  => 'bu.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Burundi',
                    'slug'  => 'burundi',
                    'parent'  => 0,
                    'flag'  => 'bi.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Canada',
                    'slug'  => 'canada',
                    'parent'  => 0,
                    'flag'  => 'ca.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Cabo Verde',
                    'slug'  => 'cabo-verde',
                    'parent'  => 0,
                    'flag'  => 'cv.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Cambodia',
                    'slug'  => 'cambodia',
                    'parent'  => 0,
                    'flag'  => 'cb.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Cameroon',
                    'slug'  => 'cameroon',
                    'parent'  => 0,
                    'flag'  => 'cm.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Central African Republic',
                    'slug'  => 'central-african-republic',
                    'parent'  => 0,
                    'flag'  => 'cf.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Chad',
                    'slug'  => 'chad',
                    'parent'  => 0,
                    'flag'  => 'ro.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Chile',
                    'slug'  => 'chile',
                    'parent'  => 0,
                    'flag'  => 'cl.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'China',
                    'slug'  => 'china',
                    'parent'  => 0,
                    'flag'  => 'cn.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Colombia',
                    'slug'  => 'colombia',
                    'parent'  => 0,
                    'flag'  => 'co.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Comoros',
                    'slug'  => 'comoros',
                    'parent'  => 0,
                    'flag'  => 'ca.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Cuba',
                    'slug'  => 'cuba',
                    'parent'  => 0,
                    'flag'  => 'cu.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Democratic Republic of the Congo',
                    'slug'  => 'democratic-depublic-of-the-congo',
                    'parent'  => 0,
                    'flag'  => 'cd.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Denmark',
                    'slug'  => 'denmark',
                    'parent'  => 0,
                    'flag'  => 'dk.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Djibouti',
                    'slug'  => 'djibouti',
                    'parent'  => 0,
                    'flag'  => 'dj.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Dominica',
                    'slug'  => 'dominica',
                    'parent'  => 0,
                    'flag'  => 'dm.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Dominican Republic',
                    'slug'  => 'dominican-republic',
                    'parent'  => 0,
                    'flag'  => 'dr.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Germany',
                    'slug'  => 'germany',
                    'parent'  => 0,
                    'flag'  => 'ger.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Indonesia',
                    'slug'  => 'indonesia',
                    'parent'  => 0,
                    'flag'  => 'id.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Pakistan',
                    'slug'  => 'pakistan',
                    'parent'  => 0,
                    'flag'  => 'pk.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Russia',
                    'slug'  => 'Russia',
                    'parent'  => 0,
                    'flag'  => 'ru.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Mexico',
                    'slug'  => 'mexico',
                    'parent'  => 0,
                    'flag'  => 'mx.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Japan',
                    'slug'  => 'japan',
                    'parent'  => 0,
                    'flag'  => 'jp.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Ethiopia',
                    'slug'  => 'ethiopia',
                    'parent'  => 0,
                    'flag'  => 'et.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Philippines',
                    'slug'  => 'philippines',
                    'parent'  => 0,
                    'flag'  => 'ph.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Egypt',
                    'slug'  => 'egypt',
                    'parent'  => 0,
                    'flag'  => 'eg.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Vietnam',
                    'slug'  => 'vietnam',
                    'parent'  => 0,
                    'flag'  => 'vn.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Iran',
                    'slug'  => 'iran',
                    'parent'  => 0,
                    'flag'  => 'ir.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Thailand',
                    'slug'  => 'thailand',
                    'parent'  => 0,
                    'flag'  => 'th.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'France',
                    'slug'  => 'france',
                    'parent'  => 0,
                    'flag'  => 'fr.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Italy',
                    'slug'  => 'italy',
                    'parent'  => 0,
                    'flag'  => 'it.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'South Africa',
                    'slug'  => 'south-africa',
                    'parent'  => 0,
                    'flag'  => 'saf.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Tanzania',
                    'slug'  => 'tanzania',
                    'parent'  => 0,
                    'flag'  => 'tz.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Kenya',
                    'slug'  => 'kenya',
                    'parent'  => 0,
                    'flag'  => 'ke.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'South Korea',
                    'slug'  => 'south-korea',
                    'parent'  => 0,
                    'flag'  => 'kr.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Spain',
                    'slug'  => 'spain',
                    'parent'  => 0,
                    'flag'  => 'es.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Uganda',
                    'slug'  => 'uganda',
                    'parent'  => 0,
                    'flag'  => 'ug.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Ukraine',
                    'slug'  => 'ukraine',
                    'parent'  => 0,
                    'flag'  => 'ua.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Sudan',
                    'slug'  => 'sudan',
                    'parent'  => 0,
                    'flag'  => 'sd.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Iraq',
                    'slug'  => 'iraq',
                    'parent'  => 0,
                    'flag'  => 'iq.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Poland',
                    'slug'  => 'poland',
                    'parent'  => 0,
                    'flag'  => 'pl.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Morocco',
                    'slug'  => 'morocco',
                    'parent'  => 0,
                    'flag'  => 'ma.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Saudi Arabia',
                    'slug'  => 'saudi-arabia',
                    'parent'  => 0,
                    'flag'  => 'sa.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Uzbekistan',
                    'slug'  => 'uzbekistan',
                    'parent'  => 0,
                    'flag'  => 'uz.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Peru',
                    'slug'  => 'peru',
                    'parent'  => 0,
                    'flag'  => 'pe.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Malaysia',
                    'slug'  => 'malaysia',
                    'parent'  => 0,
                    'flag'  => 'my.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Ghana',
                    'slug'  => 'ghana',
                    'parent'  => 0,
                    'flag'  => 'gh.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Mozambique',
                    'slug'  => 'mozambique',
                    'parent'  => 0,
                    'flag'  => 'mz.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Yemen',
                    'slug'  => 'yemen',
                    'parent'  => 0,
                    'flag'  => 'ye.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Nepal',
                    'slug'  => 'nepal',
                    'parent'  => 0,
                    'flag'  => 'np.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Venezuela',
                    'slug'  => 'venezuela',
                    'parent'  => 0,
                    'flag'  => 'vz.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Madagascar',
                    'slug'  => 'madagascar',
                    'parent'  => 0,
                    'flag'  => 'mg.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'North Korea',
                    'slug'  => 'north-korea',
                    'parent'  => 0,
                    'flag'  => 'kp.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Taiwan',
                    'slug'  => 'taiwan',
                    'parent'  => 0,
                    'flag'  => 'tw.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Niger',
                    'slug'  => 'niger',
                    'parent'  => 0,
                    'flag'  => 'ne.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Sri Lanka',
                    'slug'  => 'sri-lanka',
                    'parent'  => 0,
                    'flag'  => 'sri.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'England',
                    'slug'  => 'england',
                    'parent'  => 0,
                    'flag'  => 'en.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Mali',
                    'slug'  => 'mali',
                    'parent'  => 0,
                    'flag'  => 'ml.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Romania',
                    'slug'  => 'Romania',
                    'parent'  => 0,
                    'flag'  => 'ro.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Malawi',
                    'slug'  => 'malawi',
                    'parent'  => 0,
                    'flag'  => 'mw.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Kazakhstan',
                    'slug'  => 'kazakhstan',
                    'parent'  => 0,
                    'flag'  => 'kz.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Zambia',
                    'slug'  => 'zambia',
                    'parent'  => 0,
                    'flag'  => 'zm.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Guatemala',
                    'slug'  => 'guatemala',
                    'parent'  => 0,
                    'flag'  => 'gua.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'India',
                    'slug'  => 'india',
                    'parent'  => 0,
                    'flag'  => 'in.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Turkey',
                    'slug'  => 'turkey',
                    'parent'  => 0,
                    'flag'  => 'tr.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'United Arab Emirates',
                    'slug'  => 'united-arab-emirates',
                    'parent'  => 0,
                    'flag'  => 'ae.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'United Kingdom',
                    'slug'  => 'united-kingdom',
                    'parent'  => 0,
                    'flag'  => 'uk.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'United States',
                    'slug'  => 'united-states',
                    'parent'  => 0,
                    'flag'  => 'us.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Nigeria',
                    'slug'  => 'nigeria',
                    'parent'  => 0,
                    'flag'  => 'ng.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Ecuador',
                    'slug'  => 'ecuador',
                    'parent'  => 0,
                    'flag'  => 'et.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Netherlands',
                    'slug'  => 'netherlands',
                    'parent'  => 0,
                    'flag'  => 'nl.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Syria',
                    'slug'  => 'syria',
                    'parent'  => 0,
                    'flag'  => 'sy.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Senegal',
                    'slug'  => 'senegal',
                    'parent'  => 0,
                    'flag'  => 'sn.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Somalia',
                    'slug'  => 'somalia',
                    'parent'  => 0,
                    'flag'  => 'so.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Zimbabwe',
                    'slug'  => 'zimbabwe',
                    'parent'  => 0,
                    'flag'  => 'zw.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Guinea',
                    'slug'  => 'guinea',
                    'parent'  => 0,
                    'flag'  => 'gn.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Rwanda',
                    'slug'  => 'rwanda',
                    'parent'  => 0,
                    'flag'  => 'rw.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Tunisia',
                    'slug'  => 'tunisia',
                    'parent'  => 0,
                    'flag'  => 'tn.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Haiti',
                    'slug'  => 'haiti',
                    'parent'  => 0,
                    'flag'  => 'ht.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'South Sudan',
                    'slug'  => 'south-sudan',
                    'parent'  => 0,
                    'flag'  => 'ss.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Greece',
                    'slug'  => 'greece',
                    'parent'  => 0,
                    'flag'  => 'gr.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Portugal',
                    'slug'  => 'portugal',
                    'parent'  => 0,
                    'flag'  => 'pt.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Jordan',
                    'slug'  => 'jordan',
                    'parent'  => 0,
                    'flag'  => 'jo.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Sweden',
                    'slug'  => 'sweden',
                    'parent'  => 0,
                    'flag'  => 'se.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Honduras',
                    'slug'  => 'honduras',
                    'parent'  => 0,
                    'flag'  => 'hn.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Hungary',
                    'slug'  => 'hungary',
                    'parent'  => 0,
                    'flag'  => 'hu.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Tajikistan',
                    'slug'  => 'tajikistan',
                    'parent'  => 0,
                    'flag'  => 'tj.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Papua New Guinea',
                    'slug'  => 'papua-new-guinea',
                    'parent'  => 0,
                    'flag'  => 'pg.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Serbia',
                    'slug'  => 'serbia',
                    'parent'  => 0,
                    'flag'  => 'ser.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Switzerland',
                    'slug'  => 'switzerland',
                    'parent'  => 0,
                    'flag'  => 'ch.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Israel',
                    'slug'  => 'israel',
                    'parent'  => 0,
                    'flag'  => 'il.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Togo',
                    'slug'  => 'togo',
                    'parent'  => 0,
                    'flag'  => 'tg.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Sierra Leone',
                    'slug'  => 'sierra-leone',
                    'parent'  => 0,
                    'flag'  => 'sl.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Hong Kong',
                    'slug'  => 'hong-kong',
                    'parent'  => 0,
                    'flag'  => 'hk.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Laos',
                    'slug'  => 'laos',
                    'parent'  => 0,
                    'flag'  => 'la.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Paraguay',
                    'slug'  => 'paraguay',
                    'parent'  => 0,
                    'flag'  => 'py.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Lebanon',
                    'slug'  => 'lebanon',
                    'parent'  => 0,
                    'flag'  => 'lb.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Libya',
                    'slug'  => 'libya',
                    'parent'  => 0,
                    'flag'  => 'lib.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Nicaragua',
                    'slug'  => 'nicaragua',
                    'parent'  => 0,
                    'flag'  => 'ni.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'El Salvador',
                    'slug'  => 'el-salvador',
                    'parent'  => 0,
                    'flag'  => 'el.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Kyrgyzstan',
                    'slug'  => 'kyrgyzstan',
                    'parent'  => 0,
                    'flag'  => 'kg.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Turkmenistan',
                    'slug'  => 'turkmenistan',
                    'parent'  => 0,
                    'flag'  => 'tm.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Singapore',
                    'slug'  => 'singapore',
                    'parent'  => 0,
                    'flag'  => 'sg.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Finland',
                    'slug'  => 'finland',
                    'parent'  => 0,
                    'flag'  => 'fi.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Slovakia',
                    'slug'  => 'slovakia',
                    'parent'  => 0,
                    'flag'  => 'sk.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Norway',
                    'slug'  => 'norway',
                    'parent'  => 0,
                    'flag'  => 'no.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'State of Palestine',
                    'slug'  => 'state-of-palestine',
                    'parent'  => 0,
                    'flag'  => 'ps.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Oman',
                    'slug'  => 'oman',
                    'parent'  => 0,
                    'flag'  => 'om.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Liberia',
                    'slug'  => 'liberia',
                    'parent'  => 0,
                    'flag'  => 'lr.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'New Zealand',
                    'slug'  => 'new-zealand',
                    'parent'  => 0,
                    'flag'  => 'nz.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Mauritania',
                    'slug'  => 'mauritania',
                    'parent'  => 0,
                    'flag'  => 'mr.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Panama',
                    'slug'  => 'panama',
                    'parent'  => 0,
                    'flag'  => 'pa.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Kuwait',
                    'slug'  => 'kuwait',
                    'parent'  => 0,
                    'flag'  => 'kw.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Moldova',
                    'slug'  => 'moldova',
                    'parent'  => 0,
                    'flag'  => 'md.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Georgia',
                    'slug'  => 'georgia',
                    'parent'  => 0,
                    'flag'  => 'ge.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Eritrea',
                    'slug'  => 'eritrea',
                    'parent'  => 0,
                    'flag'  => 'er.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Uruguay',
                    'slug'  => 'uruguay',
                    'parent'  => 0,
                    'flag'  => 'uy.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Mongolia',
                    'slug'  => 'mongolia',
                    'parent'  => 0,
                    'flag'  => 'mn.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Jamaica',
                    'slug'  => 'jamaica',
                    'parent'  => 0,
                    'flag'  => 'jm.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Puerto Rico',
                    'slug'  => 'puerto-rico',
                    'parent'  => 0,
                    'flag'  => 'pr.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Qatar',
                    'slug'  => 'qatar',
                    'parent'  => 0,
                    'flag'  => 'qa.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Lithuania',
                    'slug'  => 'lithuania',
                    'parent'  => 0,
                    'flag'  => 'lt.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Namibia',
                    'slug'  => 'namibia',
                    'parent'  => 0,
                    'flag'  => 'na.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Gambia',
                    'slug'  => 'gambia',
                    'parent'  => 0,
                    'flag'  => 'gm.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Gabon',
                    'slug'  => 'gabon',
                    'parent'  => 0,
                    'flag'  => 'ga.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'North Macedonia',
                    'slug'  => 'north-macedonia',
                    'parent'  => 0,
                    'flag'  => 'mk.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Slovenia',
                    'slug'  => 'slovenia',
                    'parent'  => 0,
                    'flag'  => 'si.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Estonia',
                    'slug'  => 'estonia',
                    'parent'  => 0,
                    'flag'  => 'ei.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Macao',
                    'slug'  => 'macao',
                    'parent'  => 0,
                    'flag'  => 'mo.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ],
                [
                    'title' => 'Monaco',
                    'slug'  => 'monaco',
                    'parent'  => 0,
                    'flag'  => 'mc.png',
                    'description'  => null,
                    'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                ]
            ]
        );
    }

}
